apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ng0hngij0-dotnet-basic
  janus-idp.io/tekton: ng0hngij0-dotnet-basic
  backstage.io/kubernetes-id: ng0hngij0-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ng0hngij0-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
